## 선형대수학의 데이터 컨테이너: 행렬(Matrix)

행렬은 숫자나 변수를 직사각형 격자 형태로 배열한 것이다. 선형대수학에서 행렬은 데이터를 정리하고, 연립방정식 시스템을 표현하며, 특히 벡터를 다른 벡터로 옮기는 선형 변환(Linear Transformation)을 나타내는 가장 핵심적인 도구로 사용된다. 모든 선형 변환은 행렬 곱셈으로 표현될 수 있다.

### 행렬의 구조와 표기

- **m x n 행렬**: m개의 행(row)과 n개의 열(column)으로 구성된다.
- **성분(Element)**: 행렬의 각 위치에 있는 값. i번째 행, j번째 열에 있는 성분은 $A_{ij}$로 표기한다.
- **정방 행렬(Square Matrix)**: 행과 열의 수가 같은 행렬 (n x n).
- **단위 행렬(Identity Matrix)**: 주대각선 성분이 모두 1이고 나머지 성분은 0인 정방 행렬. 곱셈의 항등원 역할을 한다. (`I`로 표기)
- **전치 행렬(Transpose Matrix)**: 행과 열을 서로 바꾼 행렬. $A^T$로 표기한다.

### 파이썬으로 행렬 다루기

NumPy 라이브러리는 행렬을 생성하고 다양한 연산을 수행하는 데 매우 효과적이다.

In [1]:
import numpy as np

# 2x3 행렬 A 정의
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3x2 행렬 B 정의
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

print(f"행렬 A (shape: {A.shape}):\n{A}")
print(f"\n행렬 B (shape: {B.shape}):\n{B}")

행렬 A (shape: (2, 3)):
[[1 2 3]
 [4 5 6]]

행렬 B (shape: (3, 2)):
[[ 7  8]
 [ 9 10]
 [11 12]]


### 행렬의 주요 연산

#### 1. 덧셈, 뺄셈, 스칼라 곱셈
같은 크기의 행렬끼리 각 성분을 더하거나 빼고, 모든 성분에 스칼라를 곱하는 연산이다.

In [2]:
A1 = np.array([[1, 2], [3, 4]])
A2 = np.array([[5, 6], [7, 8]])
c = 3 # 스칼라

add_matrix = A1 + A2
scalar_mul_matrix = c * A1

print(f"행렬 덧셈 (A1 + A2):\n{add_matrix}")
print(f"\n스칼라 곱셈 (c * A1):\n{scalar_mul_matrix}")

행렬 덧셈 (A1 + A2):
[[ 6  8]
 [10 12]]

스칼라 곱셈 (c * A1):
[[ 3  6]
 [ 9 12]]


#### 2. 행렬 곱셈 (Matrix Multiplication)
행렬 곱셈은 선형 변환의 합성을 의미하며, 가장 중요하고 독특한 연산이다. `A @ B`는 변환 B를 적용한 후, 변환 A를 적용하는 것과 같다. 곱셈이 정의되려면 앞 행렬의 열(column) 수와 뒤 행렬의 행(row) 수가 같아야 한다.

In [3]:
# (2x3) 행렬 A와 (3x2) 행렬 B의 곱셈
# A의 열(3)과 B의 행(3)이 같으므로 곱셈 가능
C = A @ B

print(f"행렬 A (2x3):\n{A}")
print(f"\n행렬 B (3x2):\n{B}")
print(f"\n행렬 곱셈 결과 C (2x2):\n{C}")

행렬 A (2x3):
[[1 2 3]
 [4 5 6]]

행렬 B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]

행렬 곱셈 결과 C (2x2):
[[ 58  64]
 [139 154]]


#### 흔히 발생하는 실수
행렬 곱셈은 교환 법칙이 성립하지 않는다. 즉, 대부분의 경우 `A @ B ≠ B @ A` 이다. 연산의 순서가 결과에 직접적인 영향을 미친다.

### 역행렬(Inverse Matrix)
정방 행렬 `A`에 대해, 곱했을 때 단위 행렬 `I`가 나오는 행렬을 `A`의 역행렬이라 하고 $A^{-1}$로 표기한다. `A @ A⁻¹ = A⁻¹ @ A = I` 이다. 역행렬은 어떤 선형 변환을 '되돌리는' 변환에 해당한다. 행렬식이 0인 행렬(특이 행렬, Singular Matrix)은 역행렬을 갖지 않는다.

In [4]:
# 역행렬 계산
M = np.array([[2, 1],
              [4, 3]])

# M의 역행렬 계산
try:
    M_inv = np.linalg.inv(M)
    identity = M @ M_inv

    print(f"행렬 M:\n{M}")
    print(f"\nM의 역행렬 M⁻¹:\n{M_inv}")
    print(f"\nM @ M⁻¹ (결과는 단위 행렬에 가까움):\n{np.round(identity)}") # 부동소수점 오차 반올림
except np.linalg.LinAlgError as e:
    print(f"역행렬을 계산할 수 없음: {e}")

행렬 M:
[[2 1]
 [4 3]]

M의 역행렬 M⁻¹:
[[ 1.5 -0.5]
 [-2.   1. ]]

M @ M⁻¹ (결과는 단위 행렬에 가까움):
[[1. 0.]
 [0. 1.]]


#### 요약

행렬은 데이터를 담는 격자이자, 벡터 공간을 변환하는 연산자(operator) 역할을 수행하는 선형대수학의 핵심 도구이다.